import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    "install",
    "usage",
    "sessions",
    "impersonation",
    "custom-fingerprints",
    "concurrent-requests",
    "websockets",
    "low-level-curl",
    {
      type: "doc",
      id: "api/index",
      label: "API Reference",
    },
    {
      type: "category",
      label: "Standalone Requests",
      collapsed: false,
      items: [
        "api/functions/request",
        "api/functions/get",
        "api/functions/post",
        "api/functions/put",
        "api/functions/del",
        "api/functions/head",
        "api/functions/options",
        "api/functions/patch",
        "api/functions/closeSharedSession",
        "api/interfaces/RequestOptions",
        "api/interfaces/BasicAuth",
        "api/interfaces/DigestAuth",
        "api/interfaces/BearerAuth",
        "api/type-aliases/AuthType",
        "api/interfaces/ProxyConfig",
        "api/interfaces/CertConfig",
        "api/interfaces/MultipartField",
      ],
    },
    {
      type: "category",
      label: "Sessions",
      items: ["api/classes/Session", "api/interfaces/SessionOptions"],
    },
    {
      type: "category",
      label: "Request, Response, Headers, Cookies",
      items: [
        "api/classes/Request",
        "api/classes/Response",
        "api/classes/Headers",
        "api/type-aliases/HeadersInit",
        "api/classes/Cookies",
        "api/interfaces/Cookie",
        "api/interfaces/CookieOptions",
        "api/type-aliases/CookiesInit",
      ],
    },
    {
      type: "category",
      label: "Fingerprinting",
      items: [
        "api/functions/setJa3Options",
        "api/functions/setAkamaiOptions",
        "api/functions/setExtraFingerprintOptions",
        "api/interfaces/ExtraFingerprint",
        "api/classes/FingerprintError",
        "api/variables/TLS_CIPHER_NAME_MAP",
        "api/variables/TLS_EC_CURVES_MAP",
        "api/variables/TLS_VERSION_MAP",
        "api/variables/TLS_EXTENSION_NAME_MAP",
      ],
    },
    {
      type: "category",
      label: "WebSocket",
      items: [
        "api/classes/AsyncWebSocket",
        "api/functions/wsConnect",
        "api/interfaces/WebSocketOptions",
        "api/interfaces/WebSocketMessage",
        "api/interfaces/WebSocketCloseEvent",
        "api/enumerations/WebSocketMessageType",
        "api/classes/WebSocketError",
        "api/classes/WebSocketClosed",
      ],
    },
    {
      type: "category",
      label: "Low-level Curl API",
      items: [
        "api/classes/Easy",
        "api/classes/CurlMulti",
        "api/functions/getSharedMulti",
        "api/functions/closeSharedMulti",
      ],
    },
    {
      type: "category",
      label: "Platform & libcurl helpers",
      items: [
        "api/functions/resolveLibcurlPath",
        "api/functions/resolveLibrary",
        "api/functions/isUsingImpersonate",
        "api/functions/getPlatformInfo",
        "api/interfaces/LibraryInfo",
      ],
    },
    {
      type: "category",
      label: "Constants",
      link: { type: "doc", id: "api/impers/namespaces/constants/index" },
      items: [
        "api/impers/namespaces/constants/variables/CurlOpt",
        "api/impers/namespaces/constants/variables/CurlInfo",
        "api/impers/namespaces/constants/variables/CurlCode",
        "api/impers/namespaces/constants/variables/CurlMCode",
        "api/impers/namespaces/constants/variables/CurlMOpt",
        "api/impers/namespaces/constants/variables/CurlHttpVersion",
        "api/impers/namespaces/constants/variables/CurlWsFlag",
        "api/impers/namespaces/constants/variables/CurlSslVersion",
        "api/impers/namespaces/constants/variables/CurlImpersonateOpt",
      ],
    },
    {
      type: "category",
      label: "Errors",
      items: [
        "api/classes/RequestException",
        "api/classes/CurlError",
        "api/classes/ConnectionError",
        "api/classes/DNSError",
        "api/classes/ProxyError",
        "api/classes/SSLError",
        "api/classes/CertificateVerifyError",
        "api/classes/Timeout",
        "api/classes/ConnectTimeout",
        "api/classes/ReadTimeout",
        "api/classes/HTTPError",
        "api/classes/TooManyRedirects",
        "api/classes/InvalidURL",
        "api/classes/InvalidHeader",
        "api/classes/InvalidProxyURL",
        "api/classes/ImpersonateError",
        "api/classes/SessionClosed",
        "api/classes/IncompleteRead",
        "api/classes/InvalidJSONError",
        "api/classes/CookieConflict",
        "api/classes/InterfaceError",
      ],
    },
  ],
};

export default sidebars;
